#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
# Attempts to find and execute gradle wrapper jar.

APP_NAME="Qwen3TTS-Android"
APP_BASE_NAME=${0##*/}

# Find the script directory
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname "$PRG"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found"
fi

# Execute Gradle wrapper
exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS     "-Dorg.gradle.appname=$APP_BASE_NAME"     -classpath "$CLASSPATH"     org.gradle.wrapper.GradleWrapperMain     "$@"

die () {
    echo
    echo "$*"
    echo
    exit 1
}
